version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: music_app
    ports:
      - "5433:5433"

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
